### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [ ]:
# Solution Here
import numpy as np


### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [ ]:
# Solution Here
#1D
num_1d = np.array([1,2,3,4,5])
num_1d

array([1, 2, 3, 4, 5])

In [ ]:
#2D
num_2d = np.random.randint(1,10,(3,3))
num_2d

array([[7, 6, 2],
       [7, 5, 9],
       [6, 2, 7]], dtype=int32)

In [ ]:
values = np.linspace(0,5,10)
values

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [ ]:
# Solution Here
# second row third column
element = num_2d[1][2]
element


np.int32(9)

In [ ]:
# first 2 row and first 2 column
elements = num_2d[:2, :2]
elements


array([[7, 6],
       [7, 5]], dtype=int32)

In [ ]:
# modify value last row and first col to 100
num_2d[-1, 0] = 100
modify = num_2d
modify

array([[  7,   6,   2],
       [  7,   5,   9],
       [100,   2,   7]], dtype=int32)

### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [ ]:
# Solution Here
num_2d.shape
a = num_1d.reshape(5, 1)
a 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# flatten
res = a.flatten()
res

array([1, 2, 3, 4, 5])

### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [ ]:
# Solution Here
# add by five 
add_by_five = num_1d + 5
add_by_five

array([ 6,  7,  8,  9, 10])

In [ ]:
# multiply by 3
mul_by_three = num_2d * 3
mul_by_three

array([[ 21,  18,   6],
       [ 21,  15,  27],
       [300,   6,  21]], dtype=int32)

In [ ]:
# matrix multiplication 
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
mul = A.dot(B)
mul

array([[19, 22],
       [43, 50]])

### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [ ]:
# Solution Here
A = np.random.randint(0,9,(3,3))
B = np.random.randint(0,9 ,(1,3))
print(f'2D array is {A}, 1D array is {B} ')

2D array is [[0 0 5]
 [0 4 4]
 [5 4 8]], 1D array is [[3 8 1]] 


In [ ]:
res = A + B
res

array([[ 3,  8,  6],
       [ 3, 12,  5],
       [ 8, 12,  9]], dtype=int32)